// Generated by CoffeeScript 1.9.1
(function() {
  var record;

  record = {
    "id": 1,
    "name": "first record"
  };

  record.id = 2;

  Object.freeze(record);

  record.id = 3;

}).call(this);
